// Package event defines the FileAccessEvent and related types consumed by the
// deduplication pipeline.
//
// Events are typically generated by a fanotify listener or a synthetic test
// harness, then fed into a pipeline.Pipeline via a Go channel.
package event

import (
	"fmt"
	"time"

	"github.com/user/layermerkle/layer"
)

// AccessType classifies how a file was accessed.
type AccessType uint8

const (
	// AccessUnknown is a zero-value sentinel; never use intentionally.
	AccessUnknown AccessType = iota

	// AccessRead represents an O_RDONLY access. Hash reuse from lower layers
	// is safe: the file content has not changed in the current layer.
	AccessRead

	// AccessWrite represents a write to the file in the current output layer.
	// Hash reuse from lower layers is NOT safe; a fresh hash must be computed.
	AccessWrite

	// AccessCreate represents a file newly created in the output layer.
	AccessCreate

	// AccessDelete represents a whiteout / file removal recorded in the output layer.
	AccessDelete

	// AccessRename represents a rename that originated in the output layer.
	AccessRename

	// AccessChmod represents a metadata-only change (mode, ownership) in the output layer.
	AccessChmod
)

// IsMutating reports whether the access type modifies the file's content or
// existence, making hash reuse from lower layers unsafe.
func (a AccessType) IsMutating() bool {
	switch a {
	case AccessWrite, AccessCreate, AccessDelete, AccessRename, AccessChmod:
		return true
	default:
		return false
	}
}

// String returns a human-readable label for the access type.
func (a AccessType) String() string {
	switch a {
	case AccessRead:
		return "read"
	case AccessWrite:
		return "write"
	case AccessCreate:
		return "create"
	case AccessDelete:
		return "delete"
	case AccessRename:
		return "rename"
	case AccessChmod:
		return "chmod"
	default:
		return fmt.Sprintf("unknown(%d)", uint8(a))
	}
}

// FileAccessEvent is the canonical event type produced by a fanotify listener
// (or any compatible source) and consumed by the deduplication pipeline.
//
// All fields except Metadata are required.
type FileAccessEvent struct {
	// FilePath is the absolute path of the accessed file within the merged
	// (overlay) filesystem view. Must be non-empty.
	FilePath string

	// LayerStack is ordered from the lowest (oldest) base layer to the highest
	// (output) layer. The final element is the digest of the layer being
	// produced by the running ExecOp. Must have at least one element.
	LayerStack layer.Stack

	// VertexDigest identifies the ExecOp build vertex (e.g., a BuildKit
	// content-addressable vertex hash). Used for observability/hooks only;
	// the dedup engine does not key on this field.
	VertexDigest string

	// AccessType describes how the file was accessed.
	AccessType AccessType

	// Timestamp is when the access occurred. Zero values are tolerated.
	Timestamp time.Time

	// Metadata holds arbitrary key-value pairs forwarded from the event source
	// (e.g. PID, process name, mount ID). The map may be nil.
	Metadata map[string]string
}

// Validate checks that the event is well-formed.
func (e *FileAccessEvent) Validate() error {
	if e.FilePath == "" {
		return fmt.Errorf("event: FilePath is empty")
	}
	if len(e.LayerStack) == 0 {
		return fmt.Errorf("event: LayerStack is empty")
	}
	if e.AccessType == AccessUnknown {
		return fmt.Errorf("event: AccessType is unknown/unset")
	}
	return nil
}

// OutputLayer returns the topmost (output) layer digest — the layer that the
// current ExecOp is writing into.
func (e *FileAccessEvent) OutputLayer() layer.Digest {
	return e.LayerStack.MustTop()
}

// Clone returns a deep copy of the event.
func (e *FileAccessEvent) Clone() *FileAccessEvent {
	out := *e
	out.LayerStack = e.LayerStack.Clone()
	if e.Metadata != nil {
		out.Metadata = make(map[string]string, len(e.Metadata))
		for k, v := range e.Metadata {
			out.Metadata[k] = v
		}
	}
	return &out
}

// String returns a compact, human-readable summary of the event.
func (e *FileAccessEvent) String() string {
	return fmt.Sprintf("FileAccessEvent{path=%q access=%s stack=%s vertex=%s}",
		e.FilePath, e.AccessType, e.LayerStack, e.VertexDigest)
}
