/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      colors: {
        forge: {
          success: '#00FF88', warning: '#FF7700', danger: '#FF3333',
          info: '#33AAFF', accent: '#FFEE00', cyan: '#00EEFF',
          bg: '#0A0A0A', surface: '#111111', 's2': '#1A1A1A',
          border: '#2C2C2C', text: '#F0F0F0', 't2': '#B0B0B0', 't3': '#8A8A8A',
        },
        brut: {
          bg: '#0A0A0A',
          surface: '#111111',
          's2': '#1A1A1A',
          's3': '#222222',
          border: '#2C2C2C',
          'border-2': '#3C3C3C',
          'border-3': '#505050',
          accent: '#FFEE00',
          'accent-2': '#FFD700',
          'accent-dim': 'rgba(255,238,0,0.12)',
          green: '#00FF88',
          'green-dim': 'rgba(0,255,136,0.12)',
          red: '#FF3333',
          'red-dim': 'rgba(255,51,51,0.12)',
          orange: '#FF7700',
          'orange-dim': 'rgba(255,119,0,0.12)',
          blue: '#33AAFF',
          'blue-dim': 'rgba(51,170,255,0.12)',
          cyan: '#00EEFF',
          purple: '#CC44FF',
          text: '#F0F0F0',
          't2': '#B0B0B0',
          't3': '#8A8A8A',
          't4': '#555555',
        },
      },
      boxShadow: {
        'brut': '3px 3px 0 #2C2C2C',
        'brut-accent': '3px 3px 0 #FFEE00',
        'brut-green': '3px 3px 0 #00FF88',
        'brut-red': '3px 3px 0 #FF3333',
        'brut-lg': '5px 5px 0 #2C2C2C',
        'brut-lg-accent': '5px 5px 0 #FFEE00',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '2px',
        lg: '2px',
        xl: '2px',
        '2xl': '2px',
        '3xl': '2px',
        full: '9999px',
      },
      animation: {
        'marquee': 'marquee 32s linear infinite',
        'blink': 'blink 1s step-end infinite',
        'pulse-fast': 'pulse 0.8s ease-in-out infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.25s ease-out',
        'scan': 'scan 3s linear infinite',
      },
      keyframes: {
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        blink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        scan: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100%)' } },
      },
      backgroundImage: {
        'grid-brut': "linear-gradient(rgba(255,238,0,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(255,238,0,0.04) 1px, transparent 1px)",
        'dots-brut': "radial-gradient(circle, rgba(255,238,0,0.15) 1px, transparent 1px)",
        'scanline': "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.1) 2px, rgba(0,0,0,0.1) 4px)",
      },
      backgroundSize: {
        'grid-sm': '20px 20px',
        'grid-md': '40px 40px',
        'dots-sm': '16px 16px',
      },
    },
  },
  plugins: [],
};
